export const FACILITY_TYPES = Object.freeze({
  FACTORY: 'FACTORY',
  WAREHOUSE: 'WAREHOUSE',
});

export const DELIVERY_NOTE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  DISPATCHED: 'DISPATCHED',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED',
});

export const STAMP_REQUEST_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
});

export const STAMP_PAYMENT_STATUS = Object.freeze({
  UNPAID: 'UNPAID',
  PAID: 'PAID',
  VERIFIED: 'VERIFIED',
});

export const FORECAST_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  CANCELLED: 'CANCELLED',
});

export const STAMP_STOCK_EVENT_TYPE = Object.freeze({
  RETURN: 'RETURN',
  WASTAGE: 'WASTAGE',
  TRANSFER: 'TRANSFER',
});

export const STAMP_STOCK_EVENT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const STAMP_RETURN_REASON = Object.freeze({
  MANUFACTURING_STOPPED: 'MANUFACTURING_STOPPED',
  DEFECTIVE_SHEETS: 'DEFECTIVE_SHEETS',
  IMPORT_DISCREPANCY: 'IMPORT_DISCREPANCY',
  DECLARED_OUT_OF_USE: 'DECLARED_OUT_OF_USE',
  GOODS_EXCLUDED: 'GOODS_EXCLUDED',
});

export const STAMP_WASTAGE_REASON = Object.freeze({
  DAMAGED_DURING_AFFIXING: 'DAMAGED_DURING_AFFIXING',
  PRINT_QUALITY_FAILURE: 'PRINT_QUALITY_FAILURE',
  STORAGE_DAMAGE: 'STORAGE_DAMAGE',
  OTHER_VERIFIED_DAMAGE: 'OTHER_VERIFIED_DAMAGE',
});

export const STAMP_TRANSFER_REASON = Object.freeze({
  INTERNAL_REALLOCATION: 'INTERNAL_REALLOCATION',
  PRODUCTION_LINE_REBALANCING: 'PRODUCTION_LINE_REBALANCING',
});

export const STAMP_VERIFICATION_ACTOR_TYPE = Object.freeze({
  MANUFACTURER: 'MANUFACTURER',
  IMPORTER: 'IMPORTER',
  DISTRIBUTOR: 'DISTRIBUTOR',
  RETAILER: 'RETAILER',
  PUBLIC: 'PUBLIC',
  TAX_OFFICER: 'TAX_OFFICER',
});

export const STAMP_VERIFICATION_CHANNEL = Object.freeze({
  MOBILE_APP: 'MOBILE_APP',
  WEB_PORTAL: 'WEB_PORTAL',
  SCANNER: 'SCANNER',
  API: 'API',
});

export const STAMP_VERIFICATION_RESULT = Object.freeze({
  AUTHENTIC: 'AUTHENTIC',
  SUSPECT: 'SUSPECT',
  CANCELLED_UI: 'CANCELLED_UI',
  NOT_FOUND: 'NOT_FOUND',
});
