export const STAMP_LABEL_LIFECYCLE_STATUS = Object.freeze({
  GENERATED: 'GENERATED',
  ISSUED: 'ISSUED',
  ASSIGNED: 'ASSIGNED',
  APPLIED: 'APPLIED',
  ACTIVATED: 'ACTIVATED',
  TRACKED: 'TRACKED',
  VERIFIED: 'VERIFIED',
  AUDITED: 'AUDITED',
  REVOKED: 'REVOKED',
});

export const STAMP_LABEL_EVENT_TYPE = Object.freeze({
  GENERATED: 'GENERATED',
  ISSUED: 'ISSUED',
  ASSIGNED: 'ASSIGNED',
  APPLIED: 'APPLIED',
  ACTIVATED: 'ACTIVATED',
  TRACKED: 'TRACKED',
  VERIFIED: 'VERIFIED',
  AUDITED: 'AUDITED',
  ENFORCEMENT: 'ENFORCEMENT',
});

export const STAMP_LABEL_CODE_FORMAT = Object.freeze({
  GS1_DATAMATRIX: 'GS1_DATAMATRIX',
  QR: 'QR',
  DOTCODE: 'DOTCODE',
  CODE128: 'CODE128',
});

export const STAMP_LABEL_OPERATOR_TYPE = Object.freeze({
  MANUFACTURER: 'MANUFACTURER',
  IMPORTER: 'IMPORTER',
});

export const STAMP_LABEL_PACKAGE_LEVEL = Object.freeze({
  UNIT: 'UNIT',
  PACK: 'PACK',
  CARTON: 'CARTON',
  CASE: 'CASE',
});

export const STAMP_LABEL_VERIFICATION_CHANNEL = Object.freeze({
  MOBILE_APP: 'MOBILE_APP',
  WEB_PORTAL: 'WEB_PORTAL',
  SCANNER: 'SCANNER',
  API: 'API',
});

export const STAMP_LABEL_VERIFICATION_RESULT = Object.freeze({
  AUTHENTIC: 'AUTHENTIC',
  SUSPECT: 'SUSPECT',
  CANCELLED_UI: 'CANCELLED_UI',
  NOT_FOUND: 'NOT_FOUND',
});

export const STAMP_LABEL_ENFORCEMENT_ACTION = Object.freeze({
  WARNING: 'WARNING',
  HOLD: 'HOLD',
  SEIZURE: 'SEIZURE',
  REVOKE: 'REVOKE',
});
